

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import FooterGlobal from "./components/FooterGlobal";
import SessionProvider from './SessionProvider';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider>
          <Header />
          <main className='container-wide'>
           {children}
          </main>
          <FooterGlobal />
      </SessionProvider>    
      </body>
    </html>
  );
}
